---
title: "Plotting Simulation Boxplots"
author: "Pablo Morala"
date: "19/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Check if needed libraries are installed and install/load them all:
libraries = c("gtools","neuralnet","pracma","mvtnorm","ggplot2","cowplot","RColorBrewer","reshape","tikzDevice")
for (i in libraries) {
  if(!require(i,character.only = TRUE)) {
    install.packages(i)
    library(i,character.only = TRUE)
  }
}

```

```{r, include=FALSE}
# Needed functions (stored in separate R files)
source("functions/betas_from_weights.R")
source("functions/evaluate_PR.R")
source("functions/generate_normal_data.R")
source("functions/preprocesing.R")
source("functions/Automatic_example.R")
source("functions/Automatic_PR_from_NN.R")
source("functions/plot_Taylor_and_weights.R")
source("functions/reshaping_MSE_simulations.R")
```

In this file we have the code to load all the simulations of the MSE and create the boxplot figures.

# Scaled to interval $[0,1]$:

Loading the data

```{r, include=FALSE}
simulation1=readRDS("./saved_simulations/simulation1.MSE")
simulation2=readRDS("./saved_simulations/simulation2.MSE")
simulation3=readRDS("./saved_simulations/simulation3.MSE")
simulation4=readRDS("./saved_simulations/simulation4.MSE")
simulation5=readRDS("./saved_simulations/simulation5.MSE")
simulation6=readRDS("./saved_simulations/simulation6.MSE")

df1=reshaping_MSE_simulations(simulation1,"$h1=10$",5)
df2=reshaping_MSE_simulations(simulation2,"$h1=10$",3)
df3=reshaping_MSE_simulations(simulation3,"$h1=10$",7)
df4=reshaping_MSE_simulations(simulation4,"$h1=4$",5)
df5=reshaping_MSE_simulations(simulation5,"$h1=4$",3)
df6=reshaping_MSE_simulations(simulation6,"$h1=4$",7)

```

```{r}
df.first <- rbind(df2,df1, df3, df5, df4, df6)

plot1 <- ggplot(df.first, aes(x=q.Taylor, y=MSE, fill=Act.Function)) + 
  geom_boxplot() + scale_y_log10() + facet_grid(h.1 ~ .)  + labs(fill = "Activation\n Function") + xlab("Taylor approximaiton degree (q)")
plot1
```

```{r}

# Using tikzDevice to export the plots
tikz(file = 'figures/boxplots1.tex',width=6, height=3.5)
print(plot1)
dev.off()

```



# Scaled to interval $[-1,1]$

```{r, include=FALSE}
simulation7=readRDS("./saved_simulations/simulation7.MSE")
simulation8=readRDS("./saved_simulations/simulation8.MSE")
simulation9=readRDS("./saved_simulations/simulation9.MSE")
simulation10=readRDS("./saved_simulations/simulation10.MSE")
simulation11=readRDS("./saved_simulations/simulation11.MSE")
simulation12=readRDS("./saved_simulations/simulation12.MSE")

df1=reshaping_MSE_simulations(simulation7,"$h_1=10$",5)
df2=reshaping_MSE_simulations(simulation8,"$h_1=10$",3)
df3=reshaping_MSE_simulations(simulation9,"$h_1=10$",7)
df4=reshaping_MSE_simulations(simulation10,"$h_1=4$",5)
df5=reshaping_MSE_simulations(simulation11,"$h_1=4$",3)
df6=reshaping_MSE_simulations(simulation12,"$h_1=4$",7)

```

```{r}
df.second <- rbind(df2,df1, df3, df5, df4, df6)

plot2 <- ggplot(df.second, aes(x=q.Taylor, y=MSE, fill=Act.Function)) + 
  geom_boxplot() + scale_y_log10() + facet_grid(h.1 ~ .) + labs(fill = "Activation\n Function") + xlab("Taylor approximaiton degree (q)")
plot2
```

```{r}
# Using tikzDevice to export the plots
tikz(file = 'figures/boxplots2.tex',width=6, height=3.5)
print(plot2)
dev.off()
```


# Standardized data

```{r, include=FALSE}
simulation13=readRDS("./saved_simulations/simulation13.MSE")
simulation14=readRDS("./saved_simulations/simulation14.MSE")
simulation15=readRDS("./saved_simulations/simulation15.MSE")
simulation16=readRDS("./saved_simulations/simulation16.MSE")
simulation17=readRDS("./saved_simulations/simulation17.MSE")
simulation18=readRDS("./saved_simulations/simulation18.MSE")

df1=reshaping_MSE_simulations(simulation13,"$h1=10$",5)
df2=reshaping_MSE_simulations(simulation14,"$h1=10$",3)
df3=reshaping_MSE_simulations(simulation15,"$h1=10$",7)
df4=reshaping_MSE_simulations(simulation16,"$h1=4$",5)
df5=reshaping_MSE_simulations(simulation17,"$h1=4$",3)
df6=reshaping_MSE_simulations(simulation18,"$h1=4$",7)

```


```{r}
df.third <- rbind(df2,df1, df3, df5, df4, df6)

plot3 <- ggplot(df.third, aes(x=q.Taylor, y=MSE, fill=Act.Function)) + 
  geom_boxplot() + scale_y_log10() + facet_grid(h.1 ~ .) + labs(fill = "Activation\n Function") + xlab("Taylor approximaiton degree (q)")
plot3
```

```{r}
# Using tikzDevice to export the plots
tikz(file = 'figures/boxplots3.tex',width=6, height=3.5)
print(plot3)
dev.off()
```

